[build-system]
requires = [ "setuptools>=40.6.0", "wheel>=0.34.2",]
build-backend = "setuptools.build_meta"

[project]
name = "sphinx-click"
version = "0.0.0"
description = "Sphinx extension that automatically documents click applications."
readme = "README.rst"
keywords = []
dynamic = [ "requires-python", "classifiers", "dependencies",]

[[project.authors]]
name = "Stephen Finucane, Dominic Davis-Foster"
email = "dominic@davis-foster.co.uk"


[tool.black]
line-length = 88
target-version = [ "py36",]
skip-string-normalization = true
exclude = "(\n  /(\n      \\.eggs\n    | \\.git\n    | \\.tox\n    | \\.venv\n    | build\n    | dist\n  )\n)\n"

[tool.mkrecipe]
conda-channels = [ "domdfcoding",]
extras = "all"
license-key = "MIT"
package = "sphinx_click"

[project.license]
file = "LICENSE"

[project.urls]
Homepage = "https://github.com/domdfcoding/sphinx-click"
"Issue Tracker" = "https://github.com/domdfcoding/sphinx-click/issues"
"Source Code" = "https://github.com/domdfcoding/sphinx-click"
