[tool.black]
line-length = 88
target-version = ['py36']
skip-string-normalization = true
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.tox
    | \.venv
    | build
    | dist
  )
)
'''

[build-system]
requires = ["setuptools>=40.6.0", "wheel>=0.34.2"]
build-backend = "setuptools.build_meta"
