[build-system]
requires = [ "setuptools>=40.6.0", "wheel>=0.34.2",]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = [ "py36",]
skip-string-normalization = true
exclude = "(\n  /(\n      \\.eggs\n    | \\.git\n    | \\.tox\n    | \\.venv\n    | build\n    | dist\n  )\n)\n"
